name: PLDoya
main: com.github.ucchyocean.pd.PLDoya
version: 0.1.0
author: ucchy
description: ( ・´ｰ・｀)ドヤァ...
commands:
  pldoya:
    description: ( ・´ｰ・｀)ドヤァ...
    aliases: []
    usage: ( ・´ｰ・｀)ドヤァ...
    permission: pldoya
    permission-message: You don't have "<permission>" ( ・´ｰ・｀)ドヤァ...
permissions:
  pldoya:
    description: ( ・´ｰ・｀)ドヤァ...
    default: true
