name: ${project.name}
main: com.github.ucchyocean.pd.PLDoya
version: ${project.version}
author: ucchy
description: ${project.description}
commands:
  pldoya:
    description: ${project.description}
    aliases: []
    usage: ${project.description}
    permission: pldoya
    permission-message: You don't have "<permission>" ${project.description}
permissions:
  pldoya:
    description: ${project.description}
    default: true
